#!/usr/bin/env bash
# Pavilio panel launcher for Windows-WSL desktop shortcut.
#
# What it does on every launch:
#   1. starts the panel (`npm start` backgrounds it via panel/ npm run dev &)
#   2. waits for the panel to come up on 127.0.0.1
#   3. (WSL2 only) ensures the Windows-side `netsh portproxy` entry forwards
#      <port> on the host to the current WSL IP — prompts UAC ONLY if the
#      entry is missing or stale; silent no-op when already correct
#   4. enables LAN access (panel rebinds to 0.0.0.0)
#   5. prints clickable pair links with the current token + LAN IP — paste
#      or Ctrl+click in Windows Terminal to pair the Windows browser
#
# Pavilio's pairing token only rotates on explicit user action, so the link
# stays valid across panel restarts. After a rotation, just re-run the
# shortcut to get a fresh link.
#
# Why the portproxy step exists: WSL's localhost-forwarding relay only
# exposes the panel to 127.0.0.1 on the Windows host. To reach the panel
# from a phone or laptop on the same Wi-Fi, Windows needs an explicit
# `netsh portproxy` entry that forwards <hostLanIp>:<port> to <wslIp>:<port>.
# That command requires admin elevation — hence the UAC prompt the first
# time it runs (and again only if Windows ever loses the entry).

set -u
PANEL_PORT="${PANEL_PORT:-3010}"
BASE="http://127.0.0.1:${PANEL_PORT}"

cd "$(dirname "$0")/.."

npm start

echo
printf 'Waiting for panel'
for i in $(seq 1 30); do
  if curl -fsS -o /dev/null --max-time 1 "${BASE}/api/auth/status"; then
    echo " ready."
    break
  fi
  printf '.'
  sleep 0.5
done

# ---------- WSL2 portproxy self-heal ---------------------------------------
# Only runs when powershell.exe is on PATH (i.e. inside a WSL2 distro on
# Windows). On native Linux/macOS this whole block is skipped.
if command -v powershell.exe >/dev/null 2>&1; then
  WSL_IP="$(ip -4 -o addr show eth0 2>/dev/null | awk '{print $4}' | cut -d/ -f1 | head -1)"
  if [ -z "$WSL_IP" ]; then
    echo "Could not determine WSL eth0 IP — skipping portproxy check."
  else
    # Read current portproxy table; look for a row matching our port whose
    # connect IP is the current WSL IP. If found, no-op. Otherwise prompt UAC.
    PROXY_TABLE="$(powershell.exe -NoProfile -Command "netsh interface portproxy show all" 2>/dev/null | tr -d '\r')"
    NEEDS_FIX=1
    if printf '%s\n' "$PROXY_TABLE" | awk -v port="$PANEL_PORT" -v wsl="$WSL_IP" '
        $2 == port && $3 == wsl && $4 == port { found=1 }
        END { exit found ? 0 : 1 }'; then
      NEEDS_FIX=0
    fi

    if [ "$NEEDS_FIX" = 0 ]; then
      echo "Windows portproxy already forwards :${PANEL_PORT} → ${WSL_IP}:${PANEL_PORT} ✓"
    else
      echo "Windows portproxy for :${PANEL_PORT} missing or stale — UAC prompt incoming."
      echo "  (target: 0.0.0.0:${PANEL_PORT} → ${WSL_IP}:${PANEL_PORT})"
      # Mirrors the snippet generated by panel/.../LanAccessPane.tsx:
      # delete both legacy specific-IP and current 0.0.0.0 forms (idempotent),
      # add the persistent 0.0.0.0 form, then dedupe + (re)create the firewall rule.
      WIN_LAN_IP="$(powershell.exe -NoProfile -Command "(Get-NetIPAddress -AddressFamily IPv4 | Where-Object { \$_.InterfaceAlias -notmatch 'Loopback|WSL|vEthernet|Tailscale' -and \$_.IPAddress -notmatch '^169\.|^127\.' } | Select-Object -First 1).IPAddress" 2>/dev/null | tr -d '\r\n')"
      PS_PAYLOAD="netsh interface portproxy delete v4tov4 listenport=${PANEL_PORT} listenaddress=0.0.0.0 ; "
      if [ -n "$WIN_LAN_IP" ]; then
        PS_PAYLOAD="${PS_PAYLOAD}netsh interface portproxy delete v4tov4 listenport=${PANEL_PORT} listenaddress=${WIN_LAN_IP} ; "
      fi
      PS_PAYLOAD="${PS_PAYLOAD}netsh interface portproxy add v4tov4 listenport=${PANEL_PORT} listenaddress=0.0.0.0 connectport=${PANEL_PORT} connectaddress=${WSL_IP} ; "
      # Doubled single quotes — PowerShell's escape for a literal ' inside a single-quoted string.
      # Required because the whole PS_PAYLOAD is itself wrapped in single quotes by -ArgumentList below.
      PS_PAYLOAD="${PS_PAYLOAD}Get-NetFirewallRule -DisplayName ''Pavilio LAN ${PANEL_PORT}'' -EA SilentlyContinue | Remove-NetFirewallRule ; "
      PS_PAYLOAD="${PS_PAYLOAD}New-NetFirewallRule -DisplayName ''Pavilio LAN ${PANEL_PORT}'' -Direction Inbound -LocalPort ${PANEL_PORT} -Protocol TCP -Action Allow | Out-Null ; "
      PS_PAYLOAD="${PS_PAYLOAD}Write-Host DONE ; Start-Sleep 2"
      if powershell.exe -NoProfile -Command "Start-Process powershell -Verb RunAs -Wait -ArgumentList '-NoProfile','-Command','${PS_PAYLOAD}'" >/dev/null 2>&1; then
        echo "Portproxy + firewall rule updated."
      else
        echo "  UAC canceled or failed — LAN access from other devices may not work."
        echo "  Re-run the shortcut and approve the prompt to fix."
      fi
    fi
  fi
fi
# ---------- end portproxy self-heal ----------------------------------------

echo "Enabling LAN access (panel rebinds 0.0.0.0)..."
curl -fsS -X POST "${BASE}/api/mobile-access/lan/enable" >/dev/null || {
  echo "  failed — panel may not be reachable yet, exiting to bash."
  exec bash
}

STATUS="$(curl -s "${BASE}/api/mobile-access/status")"
LAN_IP="$(printf '%s' "$STATUS" | grep -o '"lanIp":"[^"]*"' | head -n 1 | cut -d'"' -f4)"
TOKEN="$(printf '%s' "$STATUS" | grep -o '#mt=[A-Za-z0-9_-]*' | head -n 1 | cut -d= -f2)"

echo
echo "===== Pavilio panel ready ====="
if [ -n "$TOKEN" ]; then
  echo "Local browser:   http://localhost:${PANEL_PORT}/#mt=${TOKEN}"
  if [ -n "$LAN_IP" ]; then
    echo "LAN devices:     http://${LAN_IP}:${PANEL_PORT}/#mt=${TOKEN}"
  fi
  echo "(Ctrl+click in Windows Terminal, or copy-paste into your browser.)"
else
  echo "(Could not extract pairing token — visit http://localhost:${PANEL_PORT} manually.)"
fi
echo
echo "Stop with: npm stop"
echo

exec bash
